// 图片生成模型（文生图）—— MODELS 按 800 行约束拆分（§5.6）
// 参数名/枚举/价格对齐国际版 llms 文档与价格表（附录 C 矩阵冻结稿，2026-10-06）
import { BZA_RATIOS_FULL, BZA_RATIOS_10_ALT, O2_I2I_RATIOS } from '../ratios';
import {
  calcO2Price, calcSeedream5Price, calcFixedPrice, calcZImageBasePrice, QWEN_IMAGE_PRICE,
} from '../pricing';

export const IMAGE_MODELS = {
  'nano-banana-2-channel': {
    name: 'Nano Banana 2（渠道）',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1k': 40, '2k': 50, '4k': 60 },
    resolutions: ['1k', '2k', '4k'],
    textToImageRatios: BZA_RATIOS_FULL,
    imageToImageRatios: BZA_RATIOS_FULL,
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'bza-image-b2-official': {
    name: 'Nano Banana 2',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '0.5K': 40, '1K': 60, '2K': 80, '4K': 110 },
    resolutions: ['0.5K', '1K', '2K', '4K'],
    textToImageRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    imageToImageRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 8,
    supportsImageToImage: true,
    supportsSeed: true, supportsWebSearch: true,
  },
  'bza-image-b-pro-base': {
    name: 'Nano Banana Pro（渠道）',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1k': 80, '2k': 80, '4k': 100 },
    resolutions: ['1k', '2k', '4k'],
    textToImageRatios: BZA_RATIOS_10_ALT,
    imageToImageRatios: BZA_RATIOS_10_ALT,
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'bza-image-b-pro-official': {
    name: 'Nano Banana Pro',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1K': 100, '2K': 120, '4K': 180 },
    resolutions: ['1K', '2K', '4K'],
    textToImageRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    imageToImageRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 8,
    supportsImageToImage: true,
    supportsSeed: true, supportsWebSearch: true,
  },
  'bza-image-o2-base': {
    name: 'GPT Image 2（渠道）',
    icon: { name: 'image-outline', color: '#10A37F' },
    manufacturer: 'openai',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1k': 30, '2k': 30, '4k': 30 },
    resolutions: ['1k', '2k', '4k'],
    defaultResolution: '2k',
    textToImageRatios: ['1:1', '2:3', '3:2', '4:5', '5:4', '3:4', '4:3', '16:9', '9:16', '21:9'],
    imageToImageRatios: O2_I2I_RATIOS,
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'bza-image-o2-official': {
    name: 'GPT Image 2',
    icon: { name: 'image-outline', color: '#10A37F' },
    manufacturer: 'openai',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'width-height-quality',
    qualities: ['auto', 'low', 'medium', 'high'],
    priceNote: '按质量×像素计费；图生图多图另收 50/张',
    priceCalculator: calcO2Price,
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 9,
    supportsImageToImage: true,
  },
  'seedream-5-0-official': {
    name: 'Seedream 5.0 Pro',
    icon: { name: 'image-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'size-only',
    priceCalculator: calcSeedream5Price,
    resolutions: ['1K', '2K'],
    defaultResolution: '2K',
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'seedream-4-5-official': {
    name: 'Seedream 4.5',
    icon: { name: 'image-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'size-only',
    priceCalculator: calcFixedPrice(60),
    resolutions: ['2K', '4K'],
    defaultResolution: '2K',
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'wan-2-7-image-official': {
    name: 'Wan 2.7 图像',
    icon: { name: 'image-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'wan-size',
    priceCalculator: calcFixedPrice(48),
    resolutions: ['1K', '2K'],
    defaultResolution: '2K',
    maxPromptLength: 5000,
    imageField: 'image_urls',
    maxImages: 9,
    supportsImageToImage: true,
    i2iResolutions: ['1K', '2K'],
    supportsSeed: true,
    supportsThinkingMode: true,
    defaultThinkingMode: true,
  },
  'wan-2-7-image-pro-official': {
    name: 'Wan 2.7 图像 Pro',
    icon: { name: 'image-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'wan-size',
    priceCalculator: calcFixedPrice(85),
    resolutions: ['1K', '2K', '4K'],
    defaultResolution: '2K',
    maxPromptLength: 5000,
    imageField: 'image_urls',
    maxImages: 9,
    supportsImageToImage: true,
    i2iResolutions: ['1K', '2K'],
    supportsSeed: true,
    supportsThinkingMode: true,
    defaultThinkingMode: true,
  },
  'z-image-turbo': {
    name: 'Z-Image Turbo',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'width-height',
    priceCalculator: calcFixedPrice(5),
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true,
    sizeRange: [480, 2048],
  },
  'qwen-image': {
    name: 'Qwen-Image',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'qwen-image',
    priceCalculator: calcFixedPrice(QWEN_IMAGE_PRICE),
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true,
    stepsRange: [4, 50], defaultSteps: 15,
    sizeRange: [480, 1536],
    guidanceScaleRange: [1, 8], defaultGuidanceScale: 4,
  },
  'z-image-base': {
    name: 'Z-Image',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'width-height',
    priceCalculator: calcZImageBasePrice,
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true, supportsSteps: true,
    stepsRange: [10, 50], defaultSteps: 28,
    sizeRange: [480, 2048],
    guidanceScaleRange: [3, 5], defaultGuidanceScale: 4,
  },
};
