// 对话与视觉理解模型—— MODELS 按 800 行约束拆分（§5.6）
// Gemini flash 系为国际版新型号（领导裁决：3 新替 4 旧），llm+vision 双 mode；
// paramType 用 vision-g（vision-g 的 params 构建含 imageUrls，llm 模式下图片为空自然不发）
import { JOYCAPTION_PRICE, calcFixedPrice } from '../pricing';

export const LLM_VISION_MODELS = {
  'gemini-3-5-flash-official': {
    name: 'Gemini 3.5 Flash',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'vision-g',
    modes: ['large-language-models', 'vision'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 1.5, output_per_1k_tokens: 9 },
    priceFormula: '国际价 M Tokens：in 1500 / out 9000；前端按 output 价估算',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    temperatureRange: [0, 2],
    enableThinkingRequired: false,
    enableSearchRequired: false,
  },
  'gemini-3-6-flash-official': {
    name: 'Gemini 3.6 Flash',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'vision-g',
    modes: ['large-language-models', 'vision'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 1.5, output_per_1k_tokens: 7.5 },
    priceFormula: '国际价 M Tokens：in 1500 / out 7500；前端按 output 价估算',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    temperatureRange: [0, 2],
    enableThinkingRequired: false,
    enableSearchRequired: false,
  },
  'gemini-3-7-flash-official': {
    name: 'Gemini 3.7 Flash',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'vision-g',
    modes: ['large-language-models', 'vision'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 1.65, output_per_1k_tokens: 8.5 },
    priceFormula: '国际价 M Tokens：in 1650 / out 8500；前端按 output 价估算',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 8192,
    temperatureRange: [0, 2],
    enableThinkingRequired: false,
    enableSearchRequired: false,
  },
  'joycaption3': {
    name: 'JoyCaption3',
    icon: { name: 'eye-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'vision',
    paramType: 'joycaption',
    modes: ['vision'],
    outputType: 'text',
    priceCalculator: calcFixedPrice(JOYCAPTION_PRICE),
    maxImages: 1,
    captionTypes: ['Descriptive', 'Descriptive (Informal)', 'Training Prompt', 'MidJourney', 'Booru tag list', 'Booru-like tag list', 'Art Critic', 'Product Listing', 'Social Media Post'],
    captionLengths: ['any', 'very short', 'short', 'medium-length', 'long', 'very long', '30', '50'],
  },
};
