// 工具型模型（抠图 / 超分 / 去水印 / LoRA）—— MODELS 按 800 行约束拆分（§5.6）
// 国际版统一走 image_urls 数组字段；价格对齐 price_table API（2026-10-06 快照）
import {
  BIREFNET_PRICE, SEEDVR2_PRICES, FLUX_KLEIN_PRICE, KONTEXT_LORA_PRICE,
  calcByResolution, calcFixedPrice,
} from '../pricing';

export const OTHER_MODELS = {
  'birefnet-background-remover': {
    name: 'BiRefNet 抠图',
    icon: { name: 'crop-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'image-to-image',
    paramType: 'birefnet',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(BIREFNET_PRICE),
    maxImages: 1,
    supportsImageToImage: true,
    noPromptRequired: true,
  },
  'seedvr2-upscale-image': {
    name: 'SeedVR2 超分',
    icon: { name: 'expand-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'image-to-image',
    paramType: 'seedvr2',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcByResolution(SEEDVR2_PRICES, 2),
    resolutions: [720, 1080, 1440, 2160],
    defaultResolution: 1080,
    maxImages: 1,
    supportsImageToImage: true,
    supportsSeed: true,
    noPromptRequired: true,
  },
  'flux-klein-watermarker-remover': {
    name: 'Flux Klein 去水印',
    icon: { name: 'brush-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'image-to-image',
    paramType: 'flux-klein',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(FLUX_KLEIN_PRICE),
    maxImages: 1,
    supportsImageToImage: true,
    noPromptRequired: true,
  },
  'kontext-dev-lora': {
    name: 'Kontext LoRA',
    icon: { name: 'layers-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'image-to-image',
    paramType: 'kontext-lora',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(KONTEXT_LORA_PRICE),
    maxImages: 1,
    supportsImageToImage: true,
    supportsSeed: true,
  },
};
