// 视频生成模型（文生/图生/首尾帧/参考/编辑）—— MODELS 按 800 行约束拆分（§5.6）
// 参数名/枚举/价格对齐国际版 llms 文档与价格表（附录 C 矩阵冻结稿，2026-10-06）
import {
  SEEDANCE_OFFICIAL_PRICES, SEEDANCE_FAST_OFFICIAL_PRICES,
  SEEDANCE_BASE_PRICES, SEEDANCE_BASE_REF_PRICES,
  SEEDANCE_FAST_BASE_PRICES, SEEDANCE_FAST_BASE_REF_PRICES,
  KLING_O3_PRO_RATES, KLING_STD_RATES, KLING_PRO_RATES, KLING_30_STD_RATES,
  VIDU_Q3_TURBO_BASE_PRICES,
  WAN_27_VIDEO_PRICES, HAILUO_23_PRICES, HAILUO_23_FAST_PRICES, HAPPYHORSE_PRICES,
  BZA_V3_PRO_PRICES, BZA_V3_FAST_PRICES,
  BZA_V3_OFFICIAL_PRICES, BZA_V3_FAST_OFFICIAL_PRICES, BZA_V3_LITE_OFFICIAL_PRICES,
  DREAMACTOR_PRICE,
  calcSeedancePrice, calcByDuration, calcByResolutionDuration, calcByResolution,
  calcKlingPrice, calcViduQ3ProOfficialPrice, calcViduQ3TurboOfficialPrice,
  calcViduQ3ProBasePrice, calcByCombo, calcV3OfficialPrice, calcVideoGPrice,
} from '../pricing';

export const VIDEO_MODELS = {
  'seedance-2-0-official': {
    name: 'Seedance 2.0',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcSeedancePrice(SEEDANCE_OFFICIAL_PRICES),
    priceFormula: '每秒：480P=160 720P=350 1080P=720 4K=1350；flf 4K=1700；ref 有参考视频 120/260/450/900',
    resolutions: ['480p', '720p', '1080p', '4k'],
    defaultResolution: '720p',
    videoRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    defaultAspectRatio: '16:9',
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsWebSearch: true,
    // 国际版官方系 flf 首帧走 image_urls（尾帧才是 last_frame_url），与 channel 系不同
    flfFirstFrameUsesImageUrls: true,
    ratioField: 'aspect_ratio',
  },
  'seedance-2-0-base': {
    name: 'Seedance 2.0（渠道）',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcSeedancePrice({
      t2v: SEEDANCE_BASE_PRICES, flf: SEEDANCE_BASE_PRICES,
      refNoRef: SEEDANCE_BASE_PRICES, refWithRef: SEEDANCE_BASE_REF_PRICES,
    }),
    resolutions: ['480p', '720p', 'native1080p', '1080p', '2k', '4k', 'native4k'],
    defaultResolution: '720p',
    videoRatios: ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    defaultAspectRatio: 'auto',
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    defaultDuration: 5,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    supportsWebSearch: true,
    ratioField: 'aspect_ratio',
    durationType: 'number',
  },
  'seedance-2-0-fast-official': {
    name: 'Seedance 2.0 Fast',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcSeedancePrice(SEEDANCE_FAST_OFFICIAL_PRICES),
    priceFormula: '每秒：480P=140 720P=280；ref 有参考视频 85/185',
    resolutions: ['480p', '720p'],
    videoRatios: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    defaultAspectRatio: '16:9',
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsWebSearch: true,
    flfFirstFrameUsesImageUrls: true,
    ratioField: 'aspect_ratio',
  },
  'seedance-2-0-fast-base': {
    name: 'Seedance 2.0 Fast（渠道）',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcSeedancePrice({
      t2v: SEEDANCE_FAST_BASE_PRICES, flf: SEEDANCE_FAST_BASE_PRICES,
      refNoRef: SEEDANCE_FAST_BASE_PRICES, refWithRef: SEEDANCE_FAST_BASE_REF_PRICES,
    }),
    resolutions: ['480p', '720p', '1080p', '2k', '4k'],
    videoRatios: ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    defaultAspectRatio: 'auto',
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    supportsWebSearch: true,
    ratioField: 'aspect_ratio',
    durationType: 'number',
  },

  'kling-o3-pro-base': {
    name: 'Kling O3 Pro',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_O3_PRO_RATES),
    videoRatios: ['1:1', '16:9', '9:16'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsMultiShot: true,
    supportsShotType: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-o3-std-base': {
    name: 'Kling O3 Std',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_STD_RATES),
    videoRatios: ['1:1', '16:9', '9:16'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsMultiShot: true,
    supportsShotType: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-3-0-pro-base': {
    name: 'Kling 3.0 Pro',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_PRO_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2048,
    maxDuration: 15,
    minDuration: 3,
    // 国际版 3.0 系 multi_shot / aspect_ratio（t2v）/ sound 必填；flf 无 aspect_ratio
    supportsMultiShot: true,
    multiShotRequired: true,
    aspectRatioRequired: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-3-0-std-base': {
    name: 'Kling 3.0 Std',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_30_STD_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2048,
    maxDuration: 15,
    minDuration: 3,
    supportsMultiShot: true,
    multiShotRequired: true,
    aspectRatioRequired: true,
    flfAspectRatio: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-o3-4k': {
    name: 'Kling O3 4K',
    icon: { name: 'git-compare-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'reference-to-video',
    paramType: 'kling-o3-4k',
    modes: ['reference-to-video'],
    priceCalculator: calcByDuration(663),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsMultiShot: true,
    soundRequired: true,
    defaultSound: true,
  },

  'vidu-q3-pro-official': {
    name: 'Vidu Q3 Pro',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3ProOfficialPrice,
    resolutions: ['540p', '720p', '1080p'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 5000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsIsRec: true,
    supportsSeed: true,
    i2vUsesImagesField: true,
  },
  'vidu-q3-pro-base': {
    name: 'Vidu Q3 Pro（渠道）',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3ProBasePrice,
    resolutions: ['540p', '720p', '1080p'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 4000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsStyle: true,
    supportsMovementAmplitude: true,
    styleOptions: ['general', 'anime'],
  },
  'vidu-q3-turbo-official': {
    name: 'Vidu Q3 Turbo',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3TurboOfficialPrice,
    resolutions: ['540p', '720p', '1080p'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 5000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsIsRec: true,
    supportsSeed: true,
    i2vUsesImagesField: true,
  },
  'vidu-q3-turbo-base': {
    name: 'Vidu Q3 Turbo（渠道）',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcByResolutionDuration(VIDU_Q3_TURBO_BASE_PRICES, 90),
    resolutions: ['540p', '720p', '1080p'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 4000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsStyle: true,
    supportsMovementAmplitude: true,
    styleOptions: ['general', 'anime'],
  },
  'wan-2-7-official': {
    name: 'Wan 2.7 视频',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-video',
    paramType: 'wan-video',
    modes: ['text-to-video', 'reference-to-video', 'video-edit'],
    priceCalculator: calcByResolutionDuration(WAN_27_VIDEO_PRICES, 215),
    priceFormula: '每秒：720P=125 1080P=215',
    resolutions: ['720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    maxPromptLength: 5000,
    maxDuration: 15,
    minDuration: 2,
    supportsPromptExtend: true,
    supportsNegativePrompt: true,
    supportsSeed: true,
    supportsAudioSetting: true,
    supportsAudioUrl: true,
    supportsRefImages: true,
    supportsRefVideos: true,
    defaultPromptExtend: true,
  },

  'hailuo-2-3-base': {
    name: 'Hailuo 2.3',
    icon: { name: 'videocam-outline', color: '#00CEC9' },
    manufacturer: 'minimax',
    category: 'image-to-video',
    paramType: 'hailuo-video',
    modes: ['image-to-video'],
    priceCalculator: calcByCombo(HAILUO_23_PRICES, 600),
    resolutions: ['768P', '1080P'],
    videoRatios: [],
    durationOptions: [6, 10],
    resolutionDurationMap: { '768P': [6, 10], '1080P': [6] },
    maxPromptLength: 5000,
  },
  'hailuo-2-3-fast-base': {
    name: 'Hailuo 2.3 Fast',
    icon: { name: 'videocam-outline', color: '#00CEC9' },
    manufacturer: 'minimax',
    category: 'image-to-video',
    paramType: 'hailuo-video',
    modes: ['image-to-video'],
    priceCalculator: calcByCombo(HAILUO_23_FAST_PRICES, 400),
    resolutions: ['768P', '1080P'],
    videoRatios: [],
    durationOptions: [6, 10],
    resolutionDurationMap: { '1080P': [6], '768P': [6, 10] },
    maxPromptLength: 5000,
  },

  'happyhorse-1-0-official': {
    name: 'HappyHorse 1.0',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-video',
    paramType: 'happyhorse-video',
    modes: ['text-to-video', 'image-to-video', 'reference-to-video', 'video-edit'],
    priceCalculator: calcByResolutionDuration(HAPPYHORSE_PRICES, 280),
    priceFormula: '每秒：720P=180 1080P=280',
    resolutions: ['720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '4:5', '5:4'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsSeed: true,
    supportsAudioSetting: true,
    defaultAudioSetting: 'auto',
  },

  'bza-video-x-official': {
    name: 'Grok Imagine',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'grok',
    category: 'text-to-video',
    paramType: 'bza-video-x',
    modes: ['text-to-video', 'image-to-video', 'video-edit'],
    priceCalculator: calcByDuration(80),
    priceFormula: '每秒 80',
    resolutions: ['480p', '720p'],
    videoRatios: ['16:9', '1:1', '9:16'],
    durationOptions: [6, 10],
    maxPromptLength: 800,
    maxImages: 1,
  },
  'bza-video-x-base': {
    name: 'Grok Imagine（渠道）',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'grok',
    category: 'text-to-video',
    paramType: 'bza-video-x',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcByDuration(60),
    priceFormula: '每秒 60',
    aspectRatioRequired: true,
    resolutions: ['480p', '720p'],
    videoRatios: ['16:9', '2:3', '1:1', '3:2', '9:16'],
    maxDuration: 15,
    minDuration: 6,
    maxPromptLength: 20000,
    maxImages: 7,
  },

  'bza-video-v3-1-pro-base': {
    name: 'Veo 3.1 Pro',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcByResolution(BZA_V3_PRO_PRICES, 180),
    priceNote: '时长固定 8s，按分辨率计费',
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    durationOptions: [8],
    maxPromptLength: 8000,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-fast-base': {
    name: 'Veo 3.1 Fast',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcByResolution(BZA_V3_FAST_PRICES, 300),
    priceNote: '时长固定 8s，按分辨率计费',
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    durationOptions: [8],
    maxPromptLength: 8000,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-official': {
    name: 'Veo 3.1',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_OFFICIAL_PRICES),
    priceFormula: '每秒：720P/1080P 170(无音频)/350(有音频)',
    resolutions: ['720p', '1080p'],
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    supportsSeed: true,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-fast-official': {
    name: 'Veo 3.1 Fast',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_FAST_OFFICIAL_PRICES),
    priceFormula: '每秒：720P 70/90 1080P 90/100',
    resolutions: ['720p', '1080p'],
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    supportsSeed: true,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-lite-official': {
    name: 'Veo 3.1 Lite',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_LITE_OFFICIAL_PRICES),
    priceFormula: '每秒：720P 25/42 1080P 42/70',
    resolutions: ['720p', '1080p'],
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    usesFlfUrlFields: true,
  },
  'bza-video-g-omni-flash-base': {
    name: 'Gemini Omni Flash',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-g',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcVideoGPrice,
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    durationOptions: [4, 6, 8, 10],
    maxPromptLength: 2048,
    maxImages: 3,
  },

  'dreamactor-2-0-base': {
    name: 'DreamActor 2.0',
    icon: { name: 'git-compare-outline', color: '#E17055' },
    manufacturer: 'jimeng',
    category: 'reference-to-video',
    paramType: 'dreamactor',
    modes: ['reference-to-video'],
    priceCalculator: calcByDuration(DREAMACTOR_PRICE),
    priceFormula: '每秒 80',
    resolutions: [],
    videoRatios: [],
    maxPromptLength: 0,
    maxDuration: 15,
    minDuration: 3,
  },
};
