export const CATEGORIES = {
  favorite: { label: '常用', icon: 'star-outline', color: '#FFD700' },
  'text-to-image': { label: '文生图', icon: 'image-outline', color: '#007AFF' },
  'image-to-image': { label: '图生图', icon: 'images-outline', color: '#34C759' },
  'text-to-video': { label: '文生视频', icon: 'videocam-outline', color: '#FF9500' },
  'image-to-video': { label: '图生视频', icon: 'film-outline', color: '#AF52DE' },
  'flf-to-video': { label: '首尾帧生视频', icon: 'swap-horizontal-outline', color: '#FF6B6B' },
  'reference-to-video': { label: '参考视频', icon: 'film', color: '#5AC8FA' },
  'video-edit': { label: '视频编辑', icon: 'cut-outline', color: '#E17055' },
  'video-extend': { label: '视频延长', icon: 'pulse-outline', color: '#00CEC9' },
  'text-to-audio': { label: '语音合成', icon: 'mic-outline', color: '#FF2D55' },
  vision: { label: '视觉理解', icon: 'eye-outline', color: '#00C7BE' },
  language: { label: '对话模型', icon: 'chatbubbles-outline', color: '#5856D6' },
};

export const MANUFACTURERS = {
  google: { label: '谷歌', icon: 'color-palette-outline', color: '#FF9500' },
  openai: { label: 'OpenAI', icon: 'hardware-chip-outline', color: '#5AC8FA' },
  bytedance: { label: '字节跳动', icon: 'leaf-outline', color: '#34C759' },
  alibaba: { label: '阿里', icon: 'grid-outline', color: '#007AFF' },
  siliconflow: { label: '硅基流动', icon: 'flash-outline', color: '#AF52DE' },
  kuaishou: { label: '快手', icon: 'zap-outline', color: '#FF6B6B' },
  shengshuo: { label: '生数科技', icon: 'play-circle-outline', color: '#6C5CE7' },
  minimax: { label: 'MiniMax', icon: 'water-outline', color: '#00CEC9' },
  jimeng: { label: '即梦', icon: 'person-outline', color: '#E17055' },
  grok: { label: 'Grok', icon: 'videocam-outline', color: '#FF9500' },
  blackforest: { label: 'Black Forest', icon: 'image-outline', color: '#FF6B6B' },
};

export const MODEL_MANUFACTURERS = {
  'bza-image-b2-base': 'google',
  'bza-image-b2-official': 'google',
  'bza-image-b-pro-base': 'google',
  'bza-image-b-pro-official': 'google',
  'bza-image-o2-base': 'openai',
  'bza-image-o2-official': 'openai',
  'seedream-5-0-official': 'bytedance',
  'seedream-4-0-official': 'bytedance',
  'seedream-4-5-official': 'bytedance',
  'flux-kontext-pro-base': 'blackforest',
  'flux-kontext-max-base': 'blackforest',
  'wan-2-7-image-official': 'alibaba',
  'wan-2-7-image-pro-official': 'alibaba',
  'z-image-turbo': 'siliconflow',
  'bza-chat-g3-flash-official': 'google',
  'bza-chat-g3-1-flash-lite-official': 'google',
  'bza-chat-g3-1-pro-official': 'google',
  'kling-3-0-std-base': 'kuaishou',
  'kling-3-0-pro-base': 'kuaishou',
  'kling-o3-std-base': 'kuaishou',
  'kling-o3-pro-base': 'kuaishou',
  'kling-o3-4k-base': 'kuaishou',
  'vidu-q3-turbo-base': 'shengshuo',
  'vidu-q3-turbo-official': 'shengshuo',
  'vidu-q3-pro-base': 'shengshuo',
  'vidu-q3-pro-official': 'shengshuo',
  'seedance-2-0-base': 'bytedance',
  'seedance-2-0-fast-base': 'bytedance',
  'seedance-2-0-official': 'bytedance',
  'seedance-2-0-fast-official': 'bytedance',
  'hailuo-2-3-base': 'minimax',
  'hailuo-2-3-fast-base': 'minimax',
  'dreamactor-2-0-base': 'jimeng',
  'bza-video-x-base': 'grok',
  'bza-video-x-official': 'grok',
  'bza-video-v3-1-fast-base': 'google',
  'bza-video-v3-1-pro-base': 'google',
  'bza-vision-g3-flash-official': 'google',
  'bza-vision-g3-1-flash-lite-official': 'google',
  'bza-vision-g3-1-pro-official': 'google',
  'joycaption3': 'siliconflow',
  'qwen3tts-custom-voice': 'siliconflow',
  'happyhorse-1-0-official': 'alibaba',
  'ltx-2-3': 'siliconflow',
  'wan-2-5-official': 'alibaba',
  'wan-2-6-official': 'alibaba',
  'wan-2-7-extend-official': 'alibaba',
};

export const FAVORITES_MAX_COUNT = 7;

export const STORAGE_KEYS = {
  favorites: '@favorite_models',
  favoritesVersion: '@favorite_models_version',
};
