import { BZA_RATIOS_FULL, BZA_RATIOS_10, BZA_RATIOS_10_ALT, O2_I2I_RATIOS } from './ratios';
import {
  SEEDANCE_FAST_RATE, SEEDANCE_BASE_PRICES, SEEDANCE_FAST_BASE_PRICES,
  KLING_O3_PRO_RATES, KLING_PRO_RATES, KLING_STD_RATES,
  VIDU_Q3_TURBO_BASE_PRICES,
  WAN_27_VIDEO_PRICES, WAN_27_EXTEND_PRICES, WAN_I2V_PRICES,
  HAILUO_23_PRICES, HAILUO_23_FAST_PRICES, HAPPYHORSE_PRICES,
  BZA_V3_PRO_PRICES, BZA_V3_FAST_PRICES,
  BZA_V3_LITE_OFFICIAL_PRICES, BZA_V3_OFFICIAL_PRICES, BZA_V3_FAST_OFFICIAL_PRICES,
  BZA_VIDEO_X_BASE_RATE,
  LTX_PRICE, DREAMACTOR_PRICE, JOYCAPTION_PRICE, TTS_PRICE, BIREFNET_PRICE,
  ACE_STEP_PRICE, SEEDVR2_PRICES, FLUX_KLEIN_PRICE, KONTEXT_LORA_PRICE, QWEN_IMAGE_PRICE,
  calcByDuration, calcByResolutionDuration, calcByCombo, calcByResolution,
  calcO2Price, calcSeedancePrice, calcKlingPrice, calcKlingO3_4KPrice,
  calcBzaVideoXPrice, calcZImagePrice, calcViduQ3ProBasePrice,
  calcViduQ3ProOfficialPrice, calcViduQ3TurboOfficialPrice,
  calcFixedPrice, calcV3OfficialPrice, calcVideoGPrice,
} from './pricing';

// ─── Re-export for backward compatibility ──────────────────────────────────────
export {
  O2_PRICE_TIERS, SEEDANCE_RATES, SEEDANCE_FAST_RATE, SEEDANCE_BASE_PRICES, SEEDANCE_FAST_BASE_PRICES,
  KLING_O3_PRO_RATES, KLING_PRO_RATES, KLING_STD_RATES, KLING_O3_4K_RATES,
  VIDU_Q3_PRO_PRICES, VIDU_Q3_PRO_BASE_T2V_PRICES, VIDU_Q3_PRO_BASE_I2V_PRICES,
  VIDU_Q3_TURBO_PRICES, VIDU_Q3_TURBO_BASE_PRICES,
  WAN_27_VIDEO_PRICES, WAN_27_EXTEND_PRICES, WAN_I2V_PRICES,
  HAILUO_23_PRICES, HAILUO_23_FAST_PRICES, HAPPYHORSE_PRICES,
  BZA_V3_PRO_PRICES, BZA_V3_FAST_PRICES,
  BZA_V3_LITE_OFFICIAL_PRICES, BZA_V3_OFFICIAL_PRICES, BZA_V3_FAST_OFFICIAL_PRICES,
  BZA_VIDEO_G_PRICES, Z_IMAGE_PRICES, Z_IMAGE_PIXEL_THRESHOLD,
  BZA_VIDEO_X_PRICES, BZA_VIDEO_X_BASE_RATE,
  LTX_PRICE, DREAMACTOR_PRICE, JOYCAPTION_PRICE, TTS_PRICE, BIREFNET_PRICE,
  ACE_STEP_PRICE, SEEDVR2_PRICES, FLUX_KLEIN_PRICE, KONTEXT_LORA_PRICE, QWEN_IMAGE_PRICE,
  calcByDuration, calcByResolutionDuration, calcByCombo, calcByResolution,
  calcO2Price, calcSeedancePrice, calcKlingPrice, calcKlingO3_4KPrice,
  calcBzaVideoXPrice, calcZImagePrice, calcViduQ3ProBasePrice,
  calcViduQ3ProOfficialPrice, calcViduQ3TurboOfficialPrice,
  calcFixedPrice, calcV3OfficialPrice, calcVideoGPrice,
} from './pricing';

export {
  API_HOST, API_BASE, WEBAPP_API_BASE, WEBAPP_DETAIL_URL,
  COMMUNITY_API_BASE, DICT_API_URL,
  UPLOAD_TOKEN_URL, COMMIT_RESOURCE_URL, USER_METADATA_URL, WALLET_BALANCE_URL, ENV_API_KEY,
  REQUEST_TIMEOUT_MS, MAX_RETRIES, RETRY_DELAY_MS, POLLING_INTERVAL_MS,
  TAB_FADE_OUT_MS, TAB_FADE_IN_MS,
} from './apiConfig';

export {
  HISTORY_KEY, API_KEY_STORAGE_KEY, API_KEYS_STORAGE_KEY, ACTIVE_KEY_ID_KEY,
  ACTIVE_TAB_KEY, HOME_STATE_KEY, MODEL_STATES_KEY, TOTAL_COINS_KEY,
} from './storageKeys';

export {
  VIDEO_RESOLUTIONS, VIDEO_RATIOS, SIZE_PRESETS, STATUS_LABELS, QUALITY_LABELS,
  TAB_HOME, TAB_WEBAPP, TAB_HISTORY, PAGE_SIZE,
} from './uiConstants';

// ─── 模型定义 ──────────────────────────────────────────────────────────────────

export const MODELS = {
  'bza-image-b2-base': {
    name: 'B.2 渠道版',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1K': 200, '2K': 200, '4K': 250 },
    resolutions: ['1K', '2K', '4K'],
    textToImageRatios: BZA_RATIOS_FULL,
    imageToImageRatios: BZA_RATIOS_FULL,
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'bza-image-b2-official': {
    name: 'B.2 官方版',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '0.5K': 550, '1K': 550, '2K': 850, '4K': 1100 },
    resolutions: ['0.5K', '1K', '2K', '4K'],
    textToImageRatios: BZA_RATIOS_FULL,
    imageToImageRatios: BZA_RATIOS_FULL,
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
    supportsSeed: true, supportsWebSearch: true,
  },
  'bza-image-b-pro-base': {
    name: 'B.Pro 渠道版',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1K': 400, '2K': 400, '4K': 500 },
    resolutions: ['1K', '2K', '4K'],
    textToImageRatios: BZA_RATIOS_10_ALT,
    imageToImageRatios: BZA_RATIOS_10_ALT,
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
  },
  'bza-image-b-pro-official': {
    name: 'B.Pro 官方版',
    icon: { name: 'image-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1K': 700, '2K': 1000, '4K': 1300 },
    resolutions: ['1K', '2K', '4K'],
    textToImageRatios: BZA_RATIOS_10,
    imageToImageRatios: BZA_RATIOS_10,
    maxPromptLength: 20000,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
    supportsTemperature: true, supportsTopP: true, supportsMaxTokens: true, supportsSeed: true,
  },
  'bza-image-o2-base': {
    name: 'O.2 渠道版',
    icon: { name: 'image-outline', color: '#10A37F' },
    manufacturer: 'openai',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'resolution-ratio',
    prices: { '1K': 100, '2K': 100, '4K': 100 },
    resolutions: ['1K', '2K', '4K'],
    defaultResolution: '2K',
    textToImageRatios: ['1:1','2:3','3:2','4:5','5:4','3:4','4:3','16:9','9:16','21:9'],
    imageToImageRatios: O2_I2I_RATIOS,
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 10,
    supportsImageToImage: true,
    resolutionRequired: false,
  },
  'bza-image-o2-official': {
    name: 'O.2 官方版',
    icon: { name: 'image-outline', color: '#10A37F' },
    manufacturer: 'openai',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'width-height-quality',
    qualities: ['low', 'medium', 'high'],
    priceNote: '按尺寸+质量计费',
    priceCalculator: calcO2Price,
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 16,
    supportsImageToImage: true,
  },
  'seedream-5-0-official': {
    name: 'Seedream 5.0',
    icon: { name: 'image-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'size-only',
    prices: { '2K': 220, '3K': 220, '4K': 220 },
    resolutions: ['2K', '3K', '4K'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'seedream-4-0-official': {
    name: 'Seedream 4.0',
    icon: { name: 'image-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'size-only',
    prices: { '1K': 150, '2K': 150, '4K': 150 },
    resolutions: ['1K', '2K', '4K'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'seedream-4-5-official': {
    name: 'Seedream 4.5',
    icon: { name: 'image-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'size-only',
    prices: { '2K': 250, '4K': 250 },
    resolutions: ['2K', '4K'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'flux-kontext-pro-base': {
    name: 'F.K Pro',
    icon: { name: 'image-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'flux-kontext',
    prices: { default: 70 },
    textToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    imageToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'flux-kontext-max-base': {
    name: 'F.K Max',
    icon: { name: 'image-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'flux-kontext',
    prices: { default: 140 },
    textToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    imageToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'bza-image-f-k-pro-base': {
    name: 'F.K.Pro 新版',
    icon: { name: 'image-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'flux-kontext',
    prices: { default: 70 },
    textToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    imageToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'bza-image-f-k-max-base': {
    name: 'F.K.Max 新版',
    icon: { name: 'image-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'flux-kontext',
    prices: { default: 140 },
    textToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    imageToImageRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxPromptLength: 2500,
    imageField: 'image_urls',
    maxImages: 14,
    supportsImageToImage: true,
  },
  'wan-2-7-image-official': {
    name: '万相2.7',
    icon: { name: 'image-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'wan-size',
    prices: { '1K': 200, '2K': 200, '4K': 200 },
    resolutions: ['1K', '2K', '4K', 'Custom'],
    defaultResolution: '2K',
    maxPromptLength: 5000,
    imageField: 'images',
    maxImages: 9,
    supportsImageToImage: true,
    i2iResolutions: ['1K', '2K', 'Custom'],
    supportsSeed: true,
    supportsWatermark: true, supportsEnableSequential: true, supportsThinkingMode: true, supportsColorPalette: true, supportsBboxList: true,
    defaultWatermark: false, defaultThinkingMode: true,
  },
  'wan-2-7-image-pro-official': {
    name: '万相2.7 Pro',
    icon: { name: 'image-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-image',
    modes: ['text-to-image', 'image-to-image'],
    paramType: 'wan-size',
    prices: { '1K': 500, '2K': 500, '4K': 500 },
    resolutions: ['1K', '2K', '4K', 'Custom'],
    defaultResolution: '2K',
    maxPromptLength: 5000,
    imageField: 'images',
    maxImages: 9,
    supportsImageToImage: true,
    i2iResolutions: ['1K', '2K', 'Custom'],
    supportsSeed: true, supportsWatermark: true, supportsEnableSequential: true, supportsThinkingMode: true, supportsColorPalette: true, supportsBboxList: true,
    defaultWatermark: false, defaultThinkingMode: true,
  },
  'z-image-turbo': {
    name: 'Z-Image Turbo',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'width-height',
    prices: { '1024': 5, '2048': 10 },
    priceCalculator: calcZImagePrice,
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true, supportsBatchSize: true,
  },
  'qwen-image': {
    name: 'Qwen-Image',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'qwen-image',
    priceCalculator: calcFixedPrice(QWEN_IMAGE_PRICE),
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true,
    stepsRange: [6, 50], defaultSteps: 15,
    sizeRange: [256, 2048],
    guidanceScaleRange: [0.1, 10], defaultGuidanceScale: 4,
  },
  'seedance-2-0-official': {
    name: 'Seedance 2.0',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcSeedancePrice,
    priceFormula: '98金币/M Tokens',
    priceFormulaRefVideo: '无参考视频 98金币/M Tokens; 有参考视频 98 * 0.6/M Tokens;',
    resolutions: ['480p', '720p', '1080p'],
    videoRatios: ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    ratioField: 'aspect_ratio',
  },
  'seedance-2-0-base': {
    name: 'Seedance 2.0 渠道版',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcByResolutionDuration(SEEDANCE_BASE_PRICES, 600),
    resolutions: ['480p', '720p', 'native1080p', '1080p', '2k', '4k'],
    defaultResolution: '720p',
    videoRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    defaultAspectRatio: 'adaptive',
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    defaultDuration: 5,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    supportsWebSearch: true,
    ratioField: 'ratio',
    durationType: 'number',
  },
  'seedance-2-0-fast-official': {
    name: 'Seedance 2.0 Fast',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcByDuration(SEEDANCE_FAST_RATE),
    priceFormula: '80金币/M Tokens',
    priceFormulaRefVideo: '无参考视频 80金币/M Tokens; 有参考视频 80 * 0.6/M Tokens;',
    resolutions: ['480p', '720p'],
    videoRatios: ['auto', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    ratioField: 'aspect_ratio',
  },
  'seedance-2-0-fast-base': {
    name: 'Seedance 2.0 Fast 渠道版',
    icon: { name: 'videocam-outline', color: '#00C7BE' },
    manufacturer: 'bytedance',
    category: 'text-to-video',
    paramType: 'seedance-video',
    modes: ['text-to-video', 'flf-to-video', 'reference-to-video'],
    priceCalculator: calcByResolutionDuration(SEEDANCE_FAST_BASE_PRICES, 500),
    resolutions: ['480p', '720p', '1080p', '2k', '4k'],
    videoRatios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    maxPromptLength: 20480,
    maxDuration: 15,
    minDuration: 4,
    supportsAudio: true,
    supportsSeed: true,
    supportsReturnLastFrame: true,
    supportsWebSearch: true,
    ratioField: 'ratio',
    durationType: 'number',
  },

  'kling-o3-pro-base': {
    name: '可灵 O3 Pro',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_O3_PRO_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 1,
    supportsMultiShot: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-o3-std-base': {
    name: '可灵 O3 Std',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_STD_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 1,
    supportsMultiShot: true,
    soundRequired: true,
    defaultSound: true,
  },
  'kling-3-0-pro-base': {
    name: '可灵 3.0 Pro',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_PRO_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2048,
    maxDuration: 15,
    minDuration: 3,
    supportsSeed: true,
    flfUsesImageUrls: true,
  },
  'kling-3-0-std-base': {
    name: '可灵 3.0 Std',
    icon: { name: 'videocam-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'text-to-video',
    paramType: 'kling-video',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcKlingPrice(KLING_STD_RATES),
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2048,
    maxDuration: 15,
    minDuration: 3,
    supportsSeed: true,
    flfUsesImageUrls: true,
  },
  'kling-o3-4k': {
    name: '可灵 O3 4K',
    icon: { name: 'git-compare-outline', color: '#FF6B6B' },
    manufacturer: 'kuaishou',
    category: 'reference-to-video',
    paramType: 'kling-o3-4k',
    modes: ['reference-to-video'],
    endpoint: 'kling-o3-4k-base/reference-to-video',
    priceCalculator: calcKlingO3_4KPrice,
    videoRatios: ['16:9', '9:16', '1:1'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsMultiShot: true,
    soundRequired: true,
    defaultSound: true,
    defaultKeepOriginalSound: true,
  },

  'vidu-q3-pro-official': {
    name: 'Vidu Q3 Pro',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3ProOfficialPrice,
    resolutions: ['540P', '720P', '1080P'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 5000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsOffPeak: true,
    supportsIsRec: true,
    supportsSeed: true,
  },
  'vidu-q3-pro-base': {
    name: 'Vidu Q3 Pro 渠道版',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3ProBasePrice,
    resolutions: ['540P', '720P', '1080P'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 4000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsStyle: true,
    supportsMovementAmplitude: true,
    flfUsesFirstFrameImage: true, styleOptions: ['general', 'anime'],
  },
  'vidu-q3-turbo-official': {
    name: 'Vidu Q3 Turbo',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcViduQ3TurboOfficialPrice,
    resolutions: ['540P', '720P', '1080P'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 5000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsOffPeak: true,
    supportsIsRec: true,
    supportsSeed: true,
  },
  'vidu-q3-turbo-base': {
    name: 'Vidu Q3 Turbo 渠道版',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'shengshuo',
    category: 'text-to-video',
    paramType: 'vidu-video',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcByResolutionDuration(VIDU_Q3_TURBO_BASE_PRICES, 200),
    resolutions: ['540P', '720P', '1080P'],
    videoRatios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
    maxPromptLength: 4000,
    maxDuration: 16,
    minDuration: 1,
    supportsAudio: true,
    supportsStyle: true,
    supportsMovementAmplitude: true,
    flfUsesFirstFrameImage: true, styleOptions: ['general', 'anime'],
  },
  'wan-2-7-official': {
    name: '万相2.7 视频',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-video',
    paramType: 'wan-video',
    modes: ['text-to-video', 'image-to-video', 'reference-to-video', 'video-edit'],
    priceCalculator: calcByResolutionDuration(WAN_27_VIDEO_PRICES, 600),
    resolutions: ['720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    maxPromptLength: 5000,
    maxDuration: 15,
    minDuration: 2,
    supportsPromptExtend: true,
    supportsWatermark: true,
    supportsNegativePrompt: true,
    supportsSeed: true,
    supportsAudioSetting: true,
    supportsDrivingAudio: true,
    supportsAudioUrl: true,
    supportsRefImages: true,
    supportsRefVideos: true,
    supportsReferenceVoice: true,
    defaultWatermark: false, defaultPromptExtend: true, defaultAudioSetting: 'auto',
  },
  'wan-2-7-extend-official': {
    name: '万相2.7 视频延长',
    icon: { name: 'time-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'video-extend',
    paramType: 'wan-video',
    modes: ['video-extend'],
    priceCalculator: calcByResolutionDuration(WAN_27_EXTEND_PRICES, 600),
    resolutions: ['720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: [],
    maxPromptLength: 2048,
    maxDuration: 15,
    minDuration: 2,
    defaultDuration: 15,
    supportsPromptExtend: true,
    supportsWatermark: true,
    supportsNegativePrompt: true,
    supportsSeed: true,
    supportsDrivingAudio: true,
    defaultWatermark: false, defaultPromptExtend: true,
  },
  'wan-2-5-official': {
    name: '万相2.5 图生视频',
    icon: { name: 'film-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'image-to-video',
    paramType: 'wan-i2v',
    modes: ['image-to-video'],
    priceCalculator: calcByResolutionDuration(WAN_I2V_PRICES, 400),
    resolutions: ['480P', '720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: [],
    maxPromptLength: 1500,
    maxDuration: 10,
    minDuration: 5,
    supportsPromptExtend: true,
    supportsAudio: true,
    supportsAudioUrl: true,
    defaultPromptExtend: true, defaultAudio: true,
  },

  'wan-2-6-official': {
    name: '万相2.6 图生视频',
    icon: { name: 'film-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'image-to-video',
    paramType: 'wan-i2v',
    modes: ['image-to-video'],
    priceCalculator: calcByResolutionDuration(WAN_I2V_PRICES, 400),
    resolutions: ['480P', '720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: [],
    maxPromptLength: 1500,
    maxDuration: 10,
    minDuration: 5,
    supportsPromptExtend: true,
    supportsAudio: true,
    supportsAudioUrl: true,
    defaultPromptExtend: true, defaultAudio: true,
  },

  'hailuo-2-3-base': {
    name: '海螺 2.3',
    icon: { name: 'videocam-outline', color: '#00CEC9' },
    manufacturer: 'minimax',
    category: 'text-to-video',
    paramType: 'hailuo-video',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcByCombo(HAILUO_23_PRICES, 1600),
    resolutions: ['768P', '1080P'],
    videoRatios: [],
    durationOptions: [6, 10],
    resolutionDurationMap: { '768P': [6, 10], '1080P': [6] },
    maxPromptLength: 2000,
    supportsPromptOptimizer: true,
    supportsFastPretreatment: true,
    supportsWatermark: true,
  },
  'hailuo-2-3-fast-base': {
    name: '海螺 2.3 Fast',
    icon: { name: 'videocam-outline', color: '#00CEC9' },
    manufacturer: 'minimax',
    category: 'text-to-video',
    paramType: 'hailuo-video',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcByCombo(HAILUO_23_FAST_PRICES, 1080),
    resolutions: ['768P', '1080P'],
    videoRatios: [],
    durationOptions: [6, 10],
    maxPromptLength: 2000,
    resolutionDurationMap: { '1080P': [6], '768P': [6, 10] },
  },

  'happyhorse-1-0-official': {
    name: 'HappyHorse 1.0',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'alibaba',
    category: 'text-to-video',
    paramType: 'happyhorse-video',
    modes: ['text-to-video', 'image-to-video', 'reference-to-video', 'video-edit'],
    priceCalculator: calcByResolutionDuration(HAPPYHORSE_PRICES, 900),
    resolutions: ['720P', '1080P'],
    defaultResolution: '1080P',
    videoRatios: ['16:9', '9:16', '1:1', '4:3', '3:4', '4:5', '5:4'],
    maxPromptLength: 2500,
    maxDuration: 15,
    minDuration: 3,
    supportsWatermark: true,
    supportsAudioSetting: true,
    defaultWatermark: true, defaultAudioSetting: 'auto',
  },

  'ltx-2-3': {
    name: 'LTX 2.3',
    icon: { name: 'videocam-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-video',
    paramType: 'ltx-video',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcFixedPrice(LTX_PRICE),
    resolutions: ['1080P'],
    videoRatios: [],
    maxPromptLength: 2500,
    maxDuration: 5,
    minDuration: 5,
    displayOptions: ['horizontal', 'vertical'],
    supportsSeed: true,
  },

  'bza-video-x-official': {
    name: 'Video X 官方版',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'grok',
    category: 'text-to-video',
    paramType: 'bza-video-x',
    modes: ['text-to-video', 'image-to-video', 'video-edit'],
    priceCalculator: calcBzaVideoXPrice,
    resolutions: ['480p', '720p'],
    videoRatios: ['16:9', '2:3', '1:1', '3:2', '9:16'],
    durationOptions: [6, 10],
    maxPromptLength: 800,
    maxImages: 1,
  },
  'bza-video-x-base': {
    name: 'Video X 渠道版',
    icon: { name: 'videocam-outline', color: '#FF6A00' },
    manufacturer: 'grok',
    category: 'text-to-video',
    paramType: 'bza-video-x',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcByDuration(BZA_VIDEO_X_BASE_RATE),
    resolutions: ['480p', '720p'],
    videoRatios: ['16:9', '2:3', '1:1', '3:2', '9:16'],
    maxDuration: 30,
    minDuration: 6,
    maxPromptLength: 20000,
    maxImages: 7,
  },

  'bza-video-v3-1-pro-base': {
    name: 'Video V3.1 Pro',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcByResolution(BZA_V3_PRO_PRICES, 1000),
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    maxPromptLength: 8000,
  },
  'bza-video-v3-1-fast-base': {
    name: 'Video V3.1 Fast',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'image-to-video', 'flf-to-video'],
    priceCalculator: calcByResolution(BZA_V3_FAST_PRICES, 800),
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    maxPromptLength: 8000,
  },
  'bza-video-v3-1-official': {
    name: 'Video V3.1 官方版',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_OFFICIAL_PRICES),
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    supportsSeed: true,
    supportsNegativePrompt: true,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-fast-official': {
    name: 'Video V3.1 Fast 官方版',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_FAST_OFFICIAL_PRICES),
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    supportsSeed: true,
    supportsNegativePrompt: true,
    usesFlfUrlFields: true,
  },
  'bza-video-v3-1-lite-official': {
    name: 'Video V3.1 Lite 官方版',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-v3',
    modes: ['text-to-video', 'flf-to-video'],
    priceCalculator: calcV3OfficialPrice(BZA_V3_LITE_OFFICIAL_PRICES),
    resolutions: ['720p', '1080p'],
    videoRatios: ['16:9', '9:16'],
    maxPromptLength: 8000,
    durationOptions: [4, 6, 8],
    supportsAudio: true,
    supportsSeed: true,
    supportsNegativePrompt: true,
    usesFlfUrlFields: true,
  },
  'bza-video-g-omni-flash-base': {
    name: 'Video G.Omni Flash',
    icon: { name: 'videocam-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'text-to-video',
    paramType: 'bza-video-g',
    modes: ['text-to-video', 'image-to-video'],
    priceCalculator: calcVideoGPrice,
    resolutions: ['720p', '1080p', '4k'],
    videoRatios: ['16:9', '9:16'],
    durationOptions: [4, 6, 8, 10],
    maxPromptLength: 2048,
    maxImages: 3,
  },

  'dreamactor-2-0-base': {
    name: 'DreamActor 2.0',
    icon: { name: 'git-compare-outline', color: '#E17055' },
    manufacturer: 'jimeng',
    category: 'reference-to-video',
    paramType: 'dreamactor',
    modes: ['reference-to-video'],
    priceCalculator: calcByDuration(DREAMACTOR_PRICE),
    resolutions: [],
    videoRatios: [],
    maxPromptLength: 0,
    maxDuration: 15,
    minDuration: 3,
  },

  'bza-chat-g3-1-pro-official': {
    name: 'G.3.1 Pro',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'llm-chat',
    modes: ['large-language-models'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 14, output_per_1k_tokens: 84 },
    priceFormula: '金币：14 / 1000 * prompt_tokens + 84 / 1000 * completion_tokens',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    temperatureRange: [0, 2],
    enableThinkingRequired: true,
    enableSearchRequired: true,
  },
  'bza-chat-g3-1-flash-lite-official': {
    name: 'G.3.1 Flash-Lite',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'llm-chat',
    modes: ['large-language-models'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 1.75, output_per_1k_tokens: 10.5 },
    priceFormula: '金币：1.75 / 1000 * prompt_tokens + 10.5 / 1000 * completion_tokens',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    temperatureRange: [0, 2],
    enableThinkingRequired: true,
    enableSearchRequired: true,
  },
  'bza-chat-g3-flash-official': {
    name: 'G.3 Flash',
    icon: { name: 'chatbubbles-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'language',
    paramType: 'llm-chat',
    modes: ['large-language-models'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 3.5, output_per_1k_tokens: 21 },
    priceFormula: '金币：3.5 / 1000 * prompt_tokens + 21 / 1000 * completion_tokens',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    temperatureRange: [0, 2],
    enableThinkingRequired: false,
    enableSearchRequired: false,
  },

  'bza-vision-g3-1-pro-official': {
    name: 'G.3.1 Pro Vision',
    icon: { name: 'eye-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'vision',
    paramType: 'vision-g',
    modes: ['vision'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 14, output_per_1k_tokens: 84 },
    priceFormula: '金币：14 / 1000 * prompt_tokens + 84 / 1000 * completion_tokens',
    maxSystemPromptLength: 5000,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    maxImages: 900,
    temperatureRange: [0, 2],
    detailOptions: ['low', 'medium', 'high'],
    supportsEnableThinking: true,
  },
  'bza-vision-g3-1-flash-lite-official': {
    name: 'G.3.1 Flash-Lite Vision',
    icon: { name: 'eye-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'vision',
    paramType: 'vision-g',
    modes: ['vision'],
    outputType: 'text',
    priceCalculator: calcFixedPrice(700),
    priceFormula: '金币：1.75 / 1000 * prompt_tokens + 10.5 / 1000 * completion_tokens',
    maxSystemPromptLength: 5000,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    maxImages: 900,
    temperatureRange: [0, 2],
    detailOptions: ['low', 'medium', 'high'],
    supportsEnableThinking: true,
  },
  'bza-vision-g3-flash-official': {
    name: 'G.3 Flash Vision',
    icon: { name: 'eye-outline', color: '#4285F4' },
    manufacturer: 'google',
    category: 'vision',
    paramType: 'vision-g',
    modes: ['vision'],
    outputType: 'text',
    prices: { input_per_1k_tokens: 3.5, output_per_1k_tokens: 21 },
    priceFormula: '金币：3.5 / 1000 * prompt_tokens + 21 / 1000 * completion_tokens',
    maxSystemPromptLength: 2500,
    maxUserPromptLength: 2500,
    maxTokens: 65536,
    maxImages: 900,
    temperatureRange: [0, 2],
    detailOptions: ['low', 'medium', 'high'],
    supportsEnableThinking: true,
  },
  'joycaption3': {
    name: 'JoyCaption3',
    icon: { name: 'eye-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'vision',
    paramType: 'joycaption',
    modes: ['vision'],
    outputType: 'text',
    priceCalculator: calcFixedPrice(JOYCAPTION_PRICE),
    maxImages: 1,
    maxTokens: 512,
    defaultTemperature: 0.5,
    defaultMaxTokens: 256,
    temperatureRange: [0, 2],
    captionTypes: ['Descriptive', 'Descriptive (Informal)', 'Training Prompt', 'MidJourney', 'Booru tag list', 'Booru-like tag list', 'Art Critic', 'Product Listing', 'Social Media Post'],
    captionLengths: ['any', 'very short', 'short', 'medium-length', 'long', 'very long', '20', '30', '40', '50', '60', '70', '80', '90', '100', '110', '120', '130', '140', '150', '160', '170', '180', '190', '200', '210', '220', '230', '240', '250', '260'],
  },

  'qwen3tts-custom-voice': {
    name: 'Qwen3 TTS',
    icon: { name: 'mic-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-audio',
    paramType: 'tts',
    modes: ['text-to-audio'],
    outputType: 'audio',
    priceCalculator: calcFixedPrice(TTS_PRICE),
    voices: ['vivian', 'serena', 'uncle_fu', 'dylan', 'eric', 'ryan', 'aiden', 'ono_anna', 'sohee'],
    formats: ['wav', 'mp3', 'flac', 'pcm', 'aac', 'opus'],
    languages: ['Auto', 'Chinese', 'English', 'Japanese', 'Korean', 'German', 'French', 'Russian', 'Portuguese', 'Spanish', 'Italian'],
    maxInputLength: 2500,
    speedRange: [0.5, 2],
    defaultSpeed: 1,
    defaultVoice: 'eric',
    defaultFormat: 'mp3',
    defaultLanguage: 'Auto',
    maxTokens: 1024,
  },
  'birefnet-background-remover': {
    name: 'BiRefNet',
    icon: { name: 'crop-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'image-to-image',
    paramType: 'birefnet',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(BIREFNET_PRICE),
    imageField: 'image',
    maxImages: 1,
    supportsImageToImage: true,
    noPromptRequired: true,
  },
  'ace-step': {
    name: 'ACE Step',
    icon: { name: 'musical-notes-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-audio',
    paramType: 'ace-step',
    modes: ['text-to-audio'],
    outputType: 'audio',
    priceCalculator: calcFixedPrice(ACE_STEP_PRICE),
    maxLyricsLength: 5000,
    maxTagsLength: 500,
    durationRange: [10, 300],
    defaultDuration: 30,
    supportsSeed: true,
    noPromptRequired: true,
  },
  'seedvr2-upscale-image': {
    name: 'SeedVR2',
    icon: { name: 'expand-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'image-to-image',
    paramType: 'seedvr2',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcByResolution(SEEDVR2_PRICES, 2),
    resolutions: [720, 1080, 1440, 2160],
    defaultResolution: 1080,
    imageField: 'image',
    maxImages: 1,
    supportsImageToImage: true,
    noPromptRequired: true,
    endpoint: 'seedvr2/upscale/image',
  },
  'z-image-base': {
    name: 'Z-Image Base',
    icon: { name: 'image-outline', color: '#6C5CE7' },
    manufacturer: 'siliconflow',
    category: 'text-to-image',
    modes: ['text-to-image'],
    paramType: 'width-height',
    priceCalculator: calcFixedPrice(0),
    maxPromptLength: 2500,
    supportsImageToImage: false,
    supportsNegativePrompt: true, supportsSeed: true, supportsBatchSize: false,
    stepsRange: [4, 50], defaultSteps: 28,
    sizeRange: [256, 2048],
    guidanceScaleRange: [0.1, 8], defaultGuidanceScale: 4,
  },
  'flux-klein-watermarker-remover': {
    name: 'Flux Klein',
    icon: { name: 'brush-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'image-to-image',
    paramType: 'flux-klein',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(FLUX_KLEIN_PRICE),
    imageField: 'image',
    maxImages: 1,
    supportsImageToImage: true,
    noPromptRequired: true,
    endpoint: 'flux-klein/watermarker-remover/image-to-image',
  },
  'kontext-dev-lora': {
    name: 'Kontext LoRA',
    icon: { name: 'layers-outline', color: '#FF6B6B' },
    manufacturer: 'blackforest',
    category: 'image-to-image',
    paramType: 'kontext-lora',
    modes: ['image-to-image'],
    outputType: 'image',
    priceCalculator: calcFixedPrice(KONTEXT_LORA_PRICE),
    imageField: 'images',
    maxImages: 1,
    supportsImageToImage: true,
    supportsSeed: true,
  },
};
