export const CATEGORIES = {
  favorite: { label: '常用', icon: 'star-outline', color: '#FFD700' },
  'text-to-image': { label: '文生图', icon: 'image-outline', color: '#007AFF' },
  'image-to-image': { label: '图生图', icon: 'images-outline', color: '#34C759' },
  'text-to-video': { label: '文生视频', icon: 'videocam-outline', color: '#FF9500' },
  'image-to-video': { label: '图生视频', icon: 'film-outline', color: '#AF52DE' },
  'reference-to-video': { label: '参考视频', icon: 'film', color: '#5AC8FA' },
  'text-to-audio': { label: '语音合成', icon: 'mic-outline', color: '#FF2D55' },
  vision: { label: '视觉理解', icon: 'eye-outline', color: '#00C7BE' },
  language: { label: '对话模型', icon: 'chatbubbles-outline', color: '#5856D6' },
};

export const MANUFACTURERS = {
  google: { label: '谷歌', icon: 'color-palette-outline', color: '#FF9500' },
  openai: { label: 'OpenAI', icon: 'hardware-chip-outline', color: '#5AC8FA' },
  bytedance: { label: '字节', icon: 'leaf-outline', color: '#34C759' },
  alibaba: { label: '阿里', icon: 'grid-outline', color: '#007AFF' },
  siliconflow: { label: '硅基流动', icon: 'flash-outline', color: '#AF52DE' },
  qianwen: { label: '千问', icon: 'message-circle-outline', color: '#00C853' },
  kling: { label: '可灵', icon: 'zap-outline', color: '#FF6B6B' },
  vidu: { label: 'Vidu', icon: 'play-circle-outline', color: '#6C5CE7' },
  seedance: { label: 'Seedance', icon: 'music-outline', color: '#FD79A8' },
  hailuo: { label: '海螺', icon: 'waves-outline', color: '#00CEC9' },
  dreamactor: { label: '即梦', icon: 'film-marker-outline', color: '#E17055' },
};

export const MODEL_MANUFACTURERS = {
  'bza-image-b2-base': 'google',
  'bza-image-b2-official': 'google',
  'bza-image-b-pro-base': 'google',
  'bza-image-b-pro-official': 'google',
  'bza-image-o2-base': 'openai',
  'bza-image-o2-official': 'openai',
  'seedream-5-0-official': 'bytedance',
  'wan-2-7-image-official': 'alibaba',
  'wan-2-7-image-pro-offcial': 'alibaba',
  'wan-2-7-image-pro-official': 'alibaba',
  'z-image-turbo': 'siliconflow',
  'bza-chat-g3-flash-official': 'qianwen',
  'bza-chat-g3-1-flash-lite-official': 'qianwen',
  'bza-chat-g3-1-pro-official': 'qianwen',
  'kling-3-0-std-base': 'kling',
  'kling-3-0-pro-base': 'kling',
  'kling-o3-std-base': 'kling',
  'kling-o3-pro-base': 'kling',
  'kling-o3-4k-base': 'kling',
  'vidu-q3-turbo-base': 'vidu',
  'vidu-q3-turbo-official': 'vidu',
  'vidu-q3-pro-base': 'vidu',
  'vidu-q3-pro-official': 'vidu',
  'seedance-2-0-base': 'seedance',
  'seedance-2-0-fast-base': 'seedance',
  'seedance-2-0-official': 'seedance',
  'seedance-2-0-fast-official': 'seedance',
  'hailuo-2-3-base': 'hailuo',
  'hailuo-2-3-fast-base': 'hailuo',
  'dreamactor-2-0-base': 'dreamactor',
  'bza-video-x-base': 'alibaba',
  'bza-video-x-official': 'alibaba',
  'bza-video-v3-1-fast-base': 'alibaba',
  'bza-video-v3-1-pro-base': 'alibaba',
  'bza-vision-g3-flash-official': 'qianwen',
  'bza-vision-g3-1-flash-lite-official': 'qianwen',
  'bza-vision-g3-1-pro-official': 'qianwen',
  'joycaption3': 'alibaba',
  'qwen3tts-custom-voice': 'qianwen',
  'happyhorse-1-0-official': 'alibaba',
  'ltx-2-3': 'alibaba',
  'wan-2-5-official': 'alibaba',
  'wan-2-6-official': 'alibaba',
  'wan-2-7-offcial': 'alibaba',
  'wan-2-7-official': 'alibaba',
};

export const FAVORITES_MAX_COUNT = 7;

export const STORAGE_KEYS = {
  favorites: '@favorite_models',
  favoritesVersion: '@favorite_models_version',
};
